#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':')"

unsetopt PROMPT_SP

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
#export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export SQLITE_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/sqlite_history"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export PYLINTHOME="${XDG_DATA_HOME:-$HOME/.local/share}/pylint"
export RUSTUP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"
#export CONDARC="${XDG_CONFIG_HOME:-$HOME/.config}/conda/condarc"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export FZF_DEFAULT_COMMAND="fd . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm
# test
#export ANDROID_SDK_HOME="$XDG_CONFIG_HOME"/android
#export ANDROID_AVD_HOME="$XDG_DATA_HOME"/android/
#export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME"/android/
#export ADB_VENDOR_KEY="$XDG_CONFIG_HOME"/android
USERXSESSION="${XDG_CACHE_HOME:-$HOME/.cache}/x11/xsession"
USERXSESSIONRC="${XDG_CACHE_HOME:-$HOME/.cache}/x11/xsessionrc"
ALTUSERXSESSION="${XDG_CACHE_HOME:-$HOME/.cache}/x11/Xsession"
ERRFILE="${XDG_CACHE_HOME:-$HOME/.cache}/x11/xsession-errors"
# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &

if pacman -Qs libxft-bgra >/dev/null 2>&1; then
	# Start graphical server on user's current tty if not already running.
	[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx -- vt1 &> /dev/null
else
	echo "ERRRRRRRRRRROR!!! Please see .zprofile"
fi

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys ${XDG_DATA_HOME:-$HOME/.local/share}/larbs/ttymaps.kmap 2>/dev/null


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.025  000.025: --- NVIM STARTING ---
001.001  000.976: locale set
001.900  000.898: inits 1
001.947  000.047: window checked
001.956  000.009: parsing arguments
002.077  000.121: expanding arguments
002.221  000.144: inits 2
003.650  001.429: init highlight
003.657  000.007: waiting for UI
006.711  003.053: done waiting for UI
006.739  000.028: initialized screen early for UI
007.271  000.047  000.047: sourcing /usr/share/nvim/archlinux.vim
007.323  000.225  000.178: sourcing /etc/xdg//nvim/sysinit.vim
026.932  019.439  019.439: sourcing /home/peter/.config/nvim/plugins.vim
027.791  000.523  000.523: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
028.552  001.380  000.856: sourcing /usr/share/nvim/runtime/syntax/synload.vim
036.286  000.020  000.020: sourcing /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
036.328  000.020  000.020: sourcing /usr/share/vim/vimfiles/ftdetect/conkyrc.vim
036.371  000.024  000.024: sourcing /usr/share/vim/vimfiles/ftdetect/meson.vim
036.437  000.047  000.047: sourcing /usr/share/vim/vimfiles/ftdetect/task.vim
037.392  000.037  000.037: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/elixir.vim
037.433  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/fish.vim
037.469  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdresource.vim
037.500  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdscript.vim
037.536  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gomod.vim
037.579  000.021  000.021: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/graphql.vim
037.629  000.026  000.026: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/hcl.vim
037.672  000.020  000.020: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/julia.vim
037.743  000.034  000.034: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ledger.vim
037.801  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/nix.vim
037.849  000.016  000.016: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ql.vim
037.937  000.038  000.038: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/query.vim
037.980  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/surface.vim
038.014  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/teal.vim
038.058  000.021  000.021: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/yang.vim
038.093  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/zig.vim
038.193  000.077  000.077: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-markdown/ftdetect/markdown.vim
038.240  000.019  000.019: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/css.vim
038.281  000.021  000.021: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/graphql.vim
038.318  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/html.vim
038.359  000.021  000.021: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/javascript.vim
038.394  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/json.vim
038.430  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/less.vim
038.467  000.016  000.016: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/lua.vim
038.575  000.030  000.030: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/markdown.vim
038.614  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/php.vim
038.652  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/ruby.vim
038.696  000.021  000.021: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/scss.vim
038.731  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/svelte.vim
038.769  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/typescript.vim
038.806  000.016  000.016: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/vue.vim
038.858  000.026  000.026: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/xml.vim
038.921  000.030  000.030: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/yaml.vim
039.633  010.966  010.140: sourcing /usr/share/nvim/runtime/filetype.vim
040.858  000.623  000.623: sourcing /usr/share/nvim/runtime/scripts.vim
041.346  014.282  001.313: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
041.637  000.124  000.124: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
042.618  000.146  000.146: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
043.406  000.125  000.125: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
051.075  009.696  009.300: sourcing /home/peter/.config/nvim/colors/snappy.vim
051.644  000.422  000.422: sourcing /usr/share/nvim/runtime/syntax/nosyntax.vim
052.366  000.208  000.208: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
053.337  000.145  000.145: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
060.464  008.734  008.380: sourcing /home/peter/.config/nvim/colors/snappy.vim
060.548  008.854  000.120: sourcing /usr/share/nvim/runtime/syntax/synload.vim
060.680  009.496  000.220: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
060.797  033.809  000.336: sourcing /home/peter/.config/nvim/settings.vim
060.912  000.084  000.084: sourcing /home/peter/.config/nvim/keys.vim
061.030  000.098  000.098: sourcing /home/peter/.config/nvim/markdown-conf.vim
121.484  060.431  060.431: sourcing /home/peter/.config/nvim/plug-conf.vim
123.480  116.078  002.216: sourcing /home/peter/.config/nvim/init.vim
123.487  000.445: sourcing vimrc file(s)
123.594  000.070  000.070: sourcing /usr/share/nvim/runtime/ftplugin.vim
123.921  000.031  000.031: sourcing /usr/share/nvim/runtime/indent.vim
126.315  000.175  000.175: sourcing /usr/share/nvim/runtime/plugin/gzip.vim
126.342  000.010  000.010: sourcing /usr/share/nvim/runtime/plugin/health.vim
126.429  000.075  000.075: sourcing /usr/share/nvim/runtime/plugin/man.vim
127.007  000.167  000.167: sourcing /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
127.087  000.642  000.475: sourcing /usr/share/nvim/runtime/plugin/matchit.vim
127.219  000.117  000.117: sourcing /usr/share/nvim/runtime/plugin/matchparen.vim
127.598  000.363  000.363: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim
127.749  000.010  000.010: sourcing /home/peter/.local/share/nvim/rplugin.vim
127.757  000.129  000.119: sourcing /usr/share/nvim/runtime/plugin/rplugin.vim
127.861  000.088  000.088: sourcing /usr/share/nvim/runtime/plugin/shada.vim
127.910  000.022  000.022: sourcing /usr/share/nvim/runtime/plugin/spellfile.vim
128.050  000.121  000.121: sourcing /usr/share/nvim/runtime/plugin/tarPlugin.vim
128.143  000.068  000.068: sourcing /usr/share/nvim/runtime/plugin/tohtml.vim
128.179  000.016  000.016: sourcing /usr/share/nvim/runtime/plugin/tutor.vim
128.350  000.153  000.153: sourcing /usr/share/nvim/runtime/plugin/zipPlugin.vim
128.900  000.457  000.457: sourcing /usr/share/vim/vimfiles/plugin/fzf.vim
129.037  000.103  000.103: sourcing /usr/share/vim/vimfiles/plugin/redact_pass.vim
132.132  003.032  003.032: sourcing /home/peter/.config/nvim/plugin/packer_compiled.lua
132.388  003.228: loading plugins
134.048  000.050  000.050: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/barbar.nvim/autoload/bufferline/highlight.vim
137.894  004.905  004.855: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/barbar.nvim/plugin/bufferline.vim
138.075  000.055  000.055: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/bracey.vim/plugin/bracey.vim
138.252  000.074  000.074: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/codi.vim/plugin/codi.vim
138.546  000.156  000.156: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/emmet-vim/plugin/emmet.vim
138.813  000.119  000.119: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/galaxyline.nvim/plugin/galaxyline.vim
140.647  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/indent-blankline.nvim/autoload/indent_blankline.vim
140.872  001.919  001.902: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/indent-blankline.nvim/plugin/indent_blankline.vim
141.328  000.310  000.310: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-autopairs/plugin/nvim-autopairs.vim
141.474  000.032  000.032: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-colorizer.lua/plugin/colorizer.vim
141.686  000.110  000.110: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-compe/plugin/compe.vim
141.851  000.058  000.058: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.vim
141.989  000.034  000.034: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-toggleterm.lua/plugin/toggleterm.vim
142.176  000.087  000.087: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-tree.lua/plugin/tree.vim
142.907  000.626  000.626: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/plugin/nvim-treesitter.vim
143.127  000.022  000.022: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/elixir.vim
143.164  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/fish.vim
143.194  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdresource.vim
143.222  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdscript.vim
143.248  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gomod.vim
143.277  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/graphql.vim
143.310  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/hcl.vim
143.335  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/julia.vim
143.365  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ledger.vim
143.390  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/nix.vim
143.418  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ql.vim
143.451  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/query.vim
143.477  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/surface.vim
143.502  000.008  000.008: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/teal.vim
143.533  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/yang.vim
143.557  000.008  000.008: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/zig.vim
143.677  000.033  000.033: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-web-devicons/plugin/nvim-web-devicons.vim
144.087  000.260  000.260: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/playground/plugin/nvim-treesitter-playground.vim
144.236  000.034  000.034: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/plenary.nvim/plugin/plenary.vim
144.656  000.289  000.289: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/telescope.nvim/plugin/telescope.vim
144.998  000.227  000.227: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-closetag/plugin/closetag.vim
146.514  001.400  001.400: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-devicons/plugin/webdevicons.vim
150.405  000.485  000.485: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-easymotion/autoload/EasyMotion/highlight.vim
150.597  003.962  003.477: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-easymotion/plugin/EasyMotion.vim
150.733  000.011  000.011: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-lua-format/plugin/lua_format.vim
150.861  000.034  000.034: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-markdown/ftdetect/markdown.vim
151.178  000.243  000.243: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/plugin/prettier.vim
151.373  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/css.vim
151.404  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/graphql.vim
151.430  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/html.vim
151.456  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/javascript.vim
151.482  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/json.vim
151.507  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/less.vim
151.531  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/lua.vim
151.562  000.016  000.016: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/markdown.vim
151.590  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/php.vim
151.614  000.008  000.008: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/ruby.vim
151.638  000.008  000.008: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/scss.vim
151.662  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/svelte.vim
151.689  000.011  000.011: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/typescript.vim
151.716  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/vue.vim
151.740  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/xml.vim
151.766  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/yaml.vim
151.873  000.026  000.026: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-snippets/plugin/vimsnippets.vim
152.054  000.084  000.084: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/plugin/startify.vim
152.475  000.319  000.319: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/plugin/vsnip.vim
152.651  000.068  000.068: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/plugin/vsnip_integ.vim
152.821  000.072  000.072: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-which-key/plugin/which_key.vim
153.331  000.074  000.074: sourcing /usr/share/nvim/runtime/autoload/provider/pythonx.vim
180.838  000.260  000.260: sourcing /usr/share/nvim/runtime/autoload/remote/host.vim
180.938  027.847  027.512: sourcing /usr/share/nvim/runtime/autoload/provider/python3.vim
181.606  028.685  000.839: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimspector/plugin/vimspector.vim
182.257  000.288  000.288: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimwiki.git/autoload/vimwiki/vars.vim
183.330  000.079  000.079: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimwiki.git/autoload/vimwiki/u.vim
185.309  003.536  003.169: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimwiki.git/plugin/vimwiki.vim
185.477  004.981: loading packages
185.649  000.024  000.024: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/autoload/vsnip_integ/integration.vim
185.758  000.044  000.044: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/autoload/vsnip_integ/detection.vim
186.834  001.272  001.204: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/after/plugin/vsnip_integ.vim
191.516  004.578  004.578: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-compe/after/plugin/compe.vim
193.475  001.885  001.885: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/compe-tabnine/after/plugin/compe_tabnine.vim
193.808  000.595: loading after plugins
193.828  000.020: inits 3
197.737  003.909: reading ShaDa
198.995  001.258: opening buffers
214.487  015.492: BufEnter autocommands
214.494  000.007: editing files in windows
216.271  000.544  000.544: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/autoload/startify.vim
216.654  000.045  000.045: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/barbar.nvim/autoload/bufferline/animate.vim
224.967  000.201  000.201: sourcing /usr/share/nvim/runtime/autoload/provider/clipboard.vim
225.407  000.283  000.283: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/syntax/startify.vim
226.016  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/syntax/startify.vim
232.328  016.749: VimEnter autocommands
232.332  000.005: UIEnter autocommands
232.336  000.003: before starting main loop
233.012  000.191  000.191: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/vsnip.vim
233.201  000.061  000.061: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/Position.vim
233.285  000.021  000.021: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip.vim
233.520  000.758  000.485: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vsnip/snippet.vim
233.732  000.094  000.094: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/TextEdit.vim
233.938  000.045  000.045: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/Text.vim
234.239  000.086  000.086: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/Vim/Buffer.vim
234.453  000.040  000.040: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/Vim/Option.vim
234.756  000.104  000.104: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/Diff.vim
234.899  002.191  001.063: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vsnip/session.vim
235.048  002.404  000.213: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vsnip.vim
236.838  002.098: first screen update
236.840  000.003: --- NVIM STARTED ---


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.007  000.007: --- NVIM STARTING ---
000.360  000.353: locale set
000.690  000.329: inits 1
000.710  000.021: window checked
000.713  000.003: parsing arguments
000.764  000.051: expanding arguments
000.815  000.051: inits 2
001.282  000.468: init highlight
001.284  000.002: waiting for UI
002.079  000.795: done waiting for UI
002.090  000.011: initialized screen early for UI
002.242  000.016  000.016: sourcing /usr/share/nvim/archlinux.vim
002.247  000.052  000.035: sourcing /etc/xdg//nvim/sysinit.vim
008.856  006.558  006.558: sourcing /home/peter/.config/nvim/plugins.vim
009.353  000.254  000.254: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
009.828  000.800  000.546: sourcing /usr/share/nvim/runtime/syntax/synload.vim
016.078  000.020  000.020: sourcing /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
016.121  000.020  000.020: sourcing /usr/share/vim/vimfiles/ftdetect/conkyrc.vim
016.165  000.024  000.024: sourcing /usr/share/vim/vimfiles/ftdetect/meson.vim
016.232  000.048  000.048: sourcing /usr/share/vim/vimfiles/ftdetect/task.vim
017.129  000.032  000.032: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/elixir.vim
017.169  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/fish.vim
017.206  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdresource.vim
017.238  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdscript.vim
017.274  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gomod.vim
017.318  000.022  000.022: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/graphql.vim
017.361  000.022  000.022: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/hcl.vim
017.394  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/julia.vim
017.435  000.019  000.019: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ledger.vim
017.468  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/nix.vim
017.506  000.016  000.016: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ql.vim
017.556  000.029  000.029: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/query.vim
017.594  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/surface.vim
017.628  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/teal.vim
017.664  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/yang.vim
017.699  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/zig.vim
017.776  000.058  000.058: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-markdown/ftdetect/markdown.vim
017.817  000.019  000.019: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/css.vim
017.854  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/graphql.vim
017.889  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/html.vim
017.927  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/javascript.vim
017.966  000.016  000.016: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/json.vim
018.010  000.026  000.026: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/less.vim
018.049  000.020  000.020: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/lua.vim
018.129  000.029  000.029: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/markdown.vim
018.164  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/php.vim
018.198  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/ruby.vim
018.239  000.020  000.020: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/scss.vim
018.273  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/svelte.vim
018.313  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/typescript.vim
018.351  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/vue.vim
018.385  000.016  000.016: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/xml.vim
018.423  000.017  000.017: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/yaml.vim
019.196  009.312  008.564: sourcing /usr/share/nvim/runtime/filetype.vim
020.404  000.500  000.500: sourcing /usr/share/nvim/runtime/scripts.vim
020.815  011.864  001.253: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
021.137  000.143  000.143: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
022.194  000.175  000.175: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
023.005  000.145  000.145: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
030.522  009.673  009.210: sourcing /home/peter/.config/nvim/colors/snappy.vim
031.109  000.430  000.430: sourcing /usr/share/nvim/runtime/syntax/nosyntax.vim
031.745  000.177  000.177: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
032.670  000.148  000.148: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
039.045  007.850  007.525: sourcing /home/peter/.config/nvim/colors/snappy.vim
039.121  007.963  000.113: sourcing /usr/share/nvim/runtime/syntax/synload.vim
039.187  008.546  000.153: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
039.307  030.413  000.329: sourcing /home/peter/.config/nvim/settings.vim
039.412  000.080  000.080: sourcing /home/peter/.config/nvim/keys.vim
039.530  000.098  000.098: sourcing /home/peter/.config/nvim/markdown-conf.vim
095.874  056.316  056.316: sourcing /home/peter/.config/nvim/plug-conf.vim
097.811  095.539  002.072: sourcing /home/peter/.config/nvim/init.vim
097.818  000.138: sourcing vimrc file(s)
097.927  000.071  000.071: sourcing /usr/share/nvim/runtime/ftplugin.vim
098.234  000.027  000.027: sourcing /usr/share/nvim/runtime/indent.vim
100.500  000.176  000.176: sourcing /usr/share/nvim/runtime/plugin/gzip.vim
100.527  000.010  000.010: sourcing /usr/share/nvim/runtime/plugin/health.vim
100.613  000.073  000.073: sourcing /usr/share/nvim/runtime/plugin/man.vim
101.203  000.173  000.173: sourcing /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
101.283  000.654  000.481: sourcing /usr/share/nvim/runtime/plugin/matchit.vim
101.412  000.114  000.114: sourcing /usr/share/nvim/runtime/plugin/matchparen.vim
101.780  000.352  000.352: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim
101.947  000.010  000.010: sourcing /home/peter/.local/share/nvim/rplugin.vim
101.954  000.146  000.136: sourcing /usr/share/nvim/runtime/plugin/rplugin.vim
102.055  000.085  000.085: sourcing /usr/share/nvim/runtime/plugin/shada.vim
102.098  000.020  000.020: sourcing /usr/share/nvim/runtime/plugin/spellfile.vim
102.236  000.119  000.119: sourcing /usr/share/nvim/runtime/plugin/tarPlugin.vim
102.327  000.065  000.065: sourcing /usr/share/nvim/runtime/plugin/tohtml.vim
102.362  000.016  000.016: sourcing /usr/share/nvim/runtime/plugin/tutor.vim
102.548  000.168  000.168: sourcing /usr/share/nvim/runtime/plugin/zipPlugin.vim
103.073  000.436  000.436: sourcing /usr/share/vim/vimfiles/plugin/fzf.vim
103.196  000.088  000.088: sourcing /usr/share/vim/vimfiles/plugin/redact_pass.vim
106.123  002.861  002.861: sourcing /home/peter/.config/nvim/plugin/packer_compiled.lua
106.376  003.076: loading plugins
108.201  000.050  000.050: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/barbar.nvim/autoload/bufferline/highlight.vim
111.946  005.172  005.122: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/barbar.nvim/plugin/bufferline.vim
112.138  000.057  000.057: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/bracey.vim/plugin/bracey.vim
112.326  000.080  000.080: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/codi.vim/plugin/codi.vim
112.777  000.251  000.251: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/emmet-vim/plugin/emmet.vim
113.103  000.179  000.179: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/galaxyline.nvim/plugin/galaxyline.vim
115.298  000.019  000.019: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/indent-blankline.nvim/autoload/indent_blankline.vim
115.645  002.396  002.377: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/indent-blankline.nvim/plugin/indent_blankline.vim
116.226  000.412  000.412: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-autopairs/plugin/nvim-autopairs.vim
116.386  000.033  000.033: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-colorizer.lua/plugin/colorizer.vim
116.638  000.136  000.136: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-compe/plugin/compe.vim
117.050  000.286  000.286: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.vim
117.211  000.039  000.039: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-toggleterm.lua/plugin/toggleterm.vim
117.425  000.101  000.101: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-tree.lua/plugin/tree.vim
118.386  000.844  000.844: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/plugin/nvim-treesitter.vim
118.633  000.028  000.028: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/elixir.vim
118.671  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/fish.vim
118.706  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdresource.vim
118.741  000.011  000.011: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdscript.vim
118.770  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/gomod.vim
118.803  000.014  000.014: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/graphql.vim
118.838  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/hcl.vim
118.866  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/julia.vim
118.900  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ledger.vim
118.928  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/nix.vim
118.959  000.011  000.011: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/ql.vim
118.995  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/query.vim
119.024  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/surface.vim
119.052  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/teal.vim
119.091  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/yang.vim
119.119  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/zig.vim
119.253  000.038  000.038: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-web-devicons/plugin/nvim-web-devicons.vim
119.801  000.378  000.378: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/playground/plugin/nvim-treesitter-playground.vim
119.966  000.038  000.038: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/plenary.nvim/plugin/plenary.vim
120.423  000.312  000.312: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/telescope.nvim/plugin/telescope.vim
120.807  000.251  000.251: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-closetag/plugin/closetag.vim
122.682  001.747  001.747: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-devicons/plugin/webdevicons.vim
127.094  000.646  000.646: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-easymotion/autoload/EasyMotion/highlight.vim
127.314  004.495  003.849: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-easymotion/plugin/EasyMotion.vim
127.459  000.013  000.013: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-lua-format/plugin/lua_format.vim
127.607  000.039  000.039: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-markdown/ftdetect/markdown.vim
127.974  000.284  000.284: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/plugin/prettier.vim
128.200  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/css.vim
128.237  000.015  000.015: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/graphql.vim
128.266  000.011  000.011: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/html.vim
128.296  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/javascript.vim
128.327  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/json.vim
128.355  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/less.vim
128.383  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/lua.vim
128.418  000.018  000.018: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/markdown.vim
128.451  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/php.vim
128.478  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/ruby.vim
128.505  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/scss.vim
128.533  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/svelte.vim
128.563  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/typescript.vim
128.594  000.010  000.010: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/vue.vim
128.622  000.009  000.009: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/xml.vim
128.651  000.011  000.011: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-prettier/ftdetect/yaml.vim
128.780  000.031  000.031: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-snippets/plugin/vimsnippets.vim
128.988  000.095  000.095: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/plugin/startify.vim
129.483  000.371  000.371: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/plugin/vsnip.vim
129.702  000.093  000.093: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/plugin/vsnip_integ.vim
129.897  000.084  000.084: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-which-key/plugin/which_key.vim
130.473  000.079  000.079: sourcing /usr/share/nvim/runtime/autoload/provider/pythonx.vim
159.098  000.299  000.299: sourcing /usr/share/nvim/runtime/autoload/remote/host.vim
159.196  028.986  028.609: sourcing /usr/share/nvim/runtime/autoload/provider/python3.vim
160.024  030.012  001.026: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimspector/plugin/vimspector.vim
160.673  000.296  000.296: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimwiki.git/autoload/vimwiki/vars.vim
161.754  000.083  000.083: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimwiki.git/autoload/vimwiki/u.vim
163.841  003.645  003.266: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vimwiki.git/plugin/vimwiki.vim
164.023  005.344: loading packages
164.204  000.026  000.026: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/autoload/vsnip_integ/integration.vim
164.313  000.043  000.043: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/autoload/vsnip_integ/detection.vim
165.420  001.307  001.239: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip-integ/after/plugin/vsnip_integ.vim
171.485  005.959  005.959: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/nvim-compe/after/plugin/compe.vim
174.156  002.586  002.586: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/compe-tabnine/after/plugin/compe_tabnine.vim
174.531  000.655: loading after plugins
174.553  000.022: inits 3
178.596  004.043: reading ShaDa
180.223  001.627: opening buffers
195.787  015.564: BufEnter autocommands
195.800  000.013: editing files in windows
197.833  000.577  000.577: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/autoload/startify.vim
198.238  000.049  000.049: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/barbar.nvim/autoload/bufferline/animate.vim
206.553  000.175  000.175: sourcing /usr/share/nvim/runtime/autoload/provider/clipboard.vim
207.014  000.293  000.293: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/syntax/startify.vim
207.635  000.012  000.012: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-startify/syntax/startify.vim
214.458  017.552: VimEnter autocommands
214.463  000.005: UIEnter autocommands
214.466  000.003: before starting main loop
215.206  000.206  000.206: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/vsnip.vim
215.410  000.066  000.066: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/Position.vim
215.500  000.022  000.022: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip.vim
215.756  000.818  000.524: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vsnip/snippet.vim
215.983  000.101  000.101: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/TextEdit.vim
216.203  000.046  000.046: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/Text.vim
216.488  000.094  000.094: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/Vim/Buffer.vim
216.721  000.043  000.043: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/Vim/Option.vim
217.051  000.114  000.114: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vital/_vsnip/VS/LSP/Diff.vim
217.209  002.328  001.112: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vsnip/session.vim
217.374  002.558  000.230: sourcing /home/peter/.local/share/nvim/site/pack/packer/start/vim-vsnip/autoload/vsnip.vim
219.283  002.259: first screen update
219.286  000.003: --- NVIM STARTED ---
